<a href="https://colab.research.google.com/github/marisaraj14/EmailSpamClassification/blob/main/Email_Spam_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Description: This programme detects whether an email is SPAM (1) or NOT SPAM (0).

In [ ]:
import numpy as np
import pandas as pd
import nltk 
from nltk.corpus import stopwords
import string

Loading Data: Emails

In [26]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


Reading the CSV File

In [27]:
df = pd.read_csv('emails.csv')

In [29]:
# First five rows in the Dataframe
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [30]:
# Print the rows and columns
df.shape

(5728, 2)

In [31]:
# Get the Columns names
df.columns

Index(['text', 'spam'], dtype='object')

In [32]:
# Check for Duplicates & removing them
df.drop_duplicates(inplace = True)

In [33]:
# Show new Shape( rows and columns)
df.shape

(5695, 2)

In [34]:
# Show the number of missing data (NAN, NaN, na) in each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [35]:
# Download the Stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [39]:
def process_text(text):
  
  #1 Remove the punctuation from the text
  #2 Remove stopwords: useless words of data
  #3 Return a list of clean text words

  #1 
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [40]:
# Show the tokenization (a list of tokens aka lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [43]:
# Example

msg1 = 'good day good good hello play'
msg2 = 'test test test test one good'
print(msg1)
print()

#Convert the text to a matric of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow1 = CountVectorizer( analyzer = process_text).fit_transform([[msg1], [msg2]])
print(bow1)

print()

print(bow1.shape)

good day good good hello play

  (0, 1)	3
  (0, 0)	1
  (0, 2)	1
  (0, 4)	1
  (1, 1)	1
  (1, 5)	4
  (1, 3)	1

(2, 6)


In [46]:
# Convert a collection of text to a matrix of tokens

from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])


In [47]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(messages_bow, df['spam'], test_size= 0.20, random_state = 0)

In [48]:
# Shape of the messages_bow
messages_bow.shape

(5695, 37229)

In [49]:
# Create and train the Naive Bayes Classifer
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, Y_train)

In [52]:
# Print the Predictions
print(classifier.predict(X_train))

# Print the Actual Values
print(Y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [58]:
# Evauate the model on the training Data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(Y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(Y_train, pred))
print()
print('Accuracy: ', accuracy_score(Y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3445   12]
 [   1 1098]]

Accuracy:  0.9971466198419666


In [59]:
# Print the Predictions
print(classifier.predict(X_test))

# Print the Actual Values
print(Y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [60]:
# Evauate the model on the test Data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(Y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(Y_test, pred))
print()
print('Accuracy: ', accuracy_score(Y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]

Accuracy:  0.9920983318700615
